version: '3.8'

services:
  anime-battle-arena:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anime-battle-arena
    restart: unless-stopped
    ports:
      - "3000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - CLIENT_URL=http://localhost:3000
    networks:
      - anime-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/characters"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.anime-battle-arena.description=Epic anime character battle game"
      - "com.anime-battle-arena.version=1.0.0"

networks:
  anime-network:
    driver: bridge